ALTER TABLE "Restaurant"
  ADD COLUMN IF NOT EXISTS "fssai" TEXT,
  ADD COLUMN IF NOT EXISTS "pricesIncludeGst" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "serviceChargePercent" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "deliveryPlatforms" TEXT[] DEFAULT ARRAY[]::TEXT[];