-- AlterTable
ALTER TABLE "DailyCounter" ADD COLUMN IF NOT EXISTS "billCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "billNumber" TEXT,
ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Table" ADD COLUMN IF NOT EXISTS "discount" DECIMAL(5,2);
