ALTER TABLE "Table"
ADD COLUMN "workflowStatus" TEXT,
ADD COLUMN "captainId" TEXT,
ADD COLUMN "guests" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "sessionStartedAt" TEXT,
ADD COLUMN "currentBill" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "kotHistory" JSONB NOT NULL DEFAULT '[]';
